### ISSUE TITLE
Add social sign-in buttons to login

### ISSUE THREAD

**Issue by mbullington** [Hack-PSU/frontend-app#6]
This is Google, Apple (on iOS), and GitHub. Really frustrating.

# Google

Requires a bunch of weird stuff: https://docs.expo.io/versions/latest/sdk/google-sign-in/

# GitHub

Almost working, but there's a **big** problem with our app (Expo sign-in) and Firebase on the web co-existing:

https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#redirect-urls

**Potential solution**: We could have a `hackpsu.org/api/auth` that would send an HTTP redirect to either Firebase or Expo based on the path afterwards. Like `hackpsu.org/api/auth/expo` and `hackpsu.org/auth/auth/firebase`.

HTTP redirect:
`hackpsu.org/api/auth/firebase` --> `https://hackpsu18.firebaseapp.com/__/auth/handler`
`hackpsu.org/api/auth/expo` --> (something, can't find rn)

@stan29308 plz help, could we have an API route for this?

# Apple

Needs Apple Developer Account, but theoretically should be rather easy: https://github.com/Hack-PSU/frontend-app/issues/5

**Comment by stan29308** [comment]
Could you clarify more?
